version: '3.2'

services:
  shentunode0:
    container_name: shentunode0
    image: "shentufoundation/shentunode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-shentud.log}
    volumes:
      - ./build:/shentu:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  shentunode1:
    container_name: shentunode1
    image: "shentufoundation/shentunode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-shentud.log}
    volumes:
      - ./build:/shentu:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  shentunode2:
    container_name: shentunode2
    image: "shentufoundation/shentunode"
    environment:
      - ID=2
      - LOG=${LOG:-shentud.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/shentu:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  shentunode3:
    container_name: shentunode3
    image: "shentufoundation/shentunode"
    environment:
      - ID=3
      - LOG=${LOG:-shentud.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/shentu:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/16
