version: '3.2'

services:
  certiknode0:
    container_name: certiknode0
    image: "certikfoundation/certiknode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-certik.log}
    volumes:
      - ./build:/certik:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  certiknode1:
    container_name: certiknode1
    image: "certikfoundation/certiknode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-certik.log}
    volumes:
      - ./build:/certik:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  certiknode2:
    container_name: certiknode2
    image: "certikfoundation/certiknode"
    environment:
      - ID=2
      - LOG=${LOG:-certik.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/certik:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  certiknode3:
    container_name: certiknode3
    image: "certikfoundation/certiknode"
    environment:
      - ID=3
      - LOG=${LOG:-certik.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/certik:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/16
